modLoader="javafml"
loaderVersion="[47,)"

[[mods]]
modId="rpgpack"
version="0.1.0"
displayName="RPGPACK - Echoes of Aincrad"
description="MMORPG system for Minecraft inspired by SAO, Elden Ring, and Genshin Impact"
authors="Hoang Anh"
logoFile=""

[[dependencies.rpgpack]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rpgpack]]
    modId="curios"
    mandatory=true
    versionRange="[5.2.0-beta.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.rpgpack]]
    modId="epicfight"
    mandatory=false
    versionRange="[1.20.1-5.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.rpgpack]]
    modId="geckolib"
    mandatory=false
    versionRange="[4.2,)"
    ordering="AFTER"
    side="BOTH"
